---
title: "Day4Comp2"
format: html
editor: visual
execute:
  warning: FALSE
---

```{r}
library(GGally)
library(skimr)
library(palmerpenguins)
library(tidyverse)
```

## Basic Data Exploration

-   names: get labels for each data set

-   dim: get data dimensions

-   head: get first n lines (6 by default)

-   tail: get last n lines (6 by default)

-   summary: get basic summary statistics

```{r}
names(penguins)

dim(penguins)

head(penguins)

tail(penguins)

summary(penguins)
```

```{r}
skim(penguins)
#if this function is the same as from another package say skimr::skin() to get skim from that specific package
```

```{r}
ggpairs(penguins)
```

## Making more exploratory charts in ggplot2

Histogram

```{r}
ggplot(data = penguins, aes(x = flipper_length_mm))+
  geom_histogram(aes(fill = species))+
  theme_minimal()
```

## Boxplot

```{r}
ggplot(data=penguins, aes(x=species,y=bill_length_mm))+
  geom_boxplot(fill = "purple", aes(color = island))+
  geom_jitter(alpha = 0.5, aes(size = bill_depth_mm))+
  theme_dark()
```
